import "HandleProcessItem.idl";

namespace WinDeleteNG
{
    [bindable]
    [default_interface]
    runtimeclass MainViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        MainViewModel();

        String SelectedFileName;
        Windows.Foundation.Collections.IObservableVector<HandleProcessItem> HandleProcessItems{ get; };
    }
}
